// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNLKcuBRd4_I-9P-SBxKe4Of1WTvFeubk',
    appId: '1:887705126175:web:6e7c749a0224819748dc2a',
    messagingSenderId: '887705126175',
    projectId: 'whats-app-f709d',
    authDomain: 'whats-app-f709d.firebaseapp.com',
    storageBucket: 'whats-app-f709d.appspot.com',
    measurementId: 'G-DEVBLTHL4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjelykLSaitYPCEk2W4STa9G7amookEHQ',
    appId: '1:887705126175:android:0ad2b06411f73d3648dc2a',
    messagingSenderId: '887705126175',
    projectId: 'whats-app-f709d',
    storageBucket: 'whats-app-f709d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLitJAbcwdQoKjgriLfqaMxgP0pEAT1c',
    appId: '1:887705126175:ios:b52d51f60c3f458648dc2a',
    messagingSenderId: '887705126175',
    projectId: 'whats-app-f709d',
    storageBucket: 'whats-app-f709d.appspot.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLitJAbcwdQoKjgriLfqaMxgP0pEAT1c',
    appId: '1:887705126175:ios:b52d51f60c3f458648dc2a',
    messagingSenderId: '887705126175',
    projectId: 'whats-app-f709d',
    storageBucket: 'whats-app-f709d.appspot.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNLKcuBRd4_I-9P-SBxKe4Of1WTvFeubk',
    appId: '1:887705126175:web:d0b0e4a7d003c3ec48dc2a',
    messagingSenderId: '887705126175',
    projectId: 'whats-app-f709d',
    authDomain: 'whats-app-f709d.firebaseapp.com',
    storageBucket: 'whats-app-f709d.appspot.com',
    measurementId: 'G-WF90F8CVDT',
  );
}
